backend/models/YoutubeVideo.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "youtube_video".
 *
 * @property int $id
 * @property int $owner_id
 * @property string $channel_id
 * @property string $channel_title
 * @property string $video_id
 * @property string $title
 * @property string $description
 * @property int $published_at
 *
 * @property User $owner
 */
class YoutubeVideo extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'youtube_video';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['owner_id', 'channel_id', 'channel_title', 'video_id', 'title', 'description', 'published_at'], 'required'],
            [['owner_id', 'published_at'], 'integer'],
            [['description'], 'string'],
            [['channel_id', 'video_id', 'owner_id'], 'string', 'max' => 255],
            [['channel_title', 'title'], 'string', 'max' => 511],
            [['video_id'], 'unique'],
            [['owner_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['owner_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'owner_id' => Yii::t('app', 'Owner ID'),
            'channel_id' => Yii::t('app', 'Channel ID'),
            'channel_title' => Yii::t('app', 'Channel Title'),
            'video_id' => Yii::t('app', 'Video ID'),
            'title' => Yii::t('app', 'Title'),
            'description' => Yii::t('app', 'Description'),
            'published_at' => Yii::t('app', 'Published At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOwner()
    {
        return $this->hasOne(User::className(), ['id' => 'owner_id']);
    }

    /**
     * @inheritdoc
     * @return YoutubeVideoQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new YoutubeVideoQuery(get_called_class());
    }
}

backend/controllers/YoutubeVideoController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\YoutubeVideo;
use backend\models\YoutubeVideoSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * YoutubeVideoController implements the CRUD actions for YoutubeVideo model.
 */
class YoutubeVideoController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
	        'access' => [
		        'class' => AccessControl::className(),
		        'rules' => [
			        [
				        'actions' => ['index', 'create', 'update', 'delete'],
				        'allow' => true,
				        'roles' => ['@'],
			        ],
		        ],
	        ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all YoutubeVideo models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new YoutubeVideoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single YoutubeVideo model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Updates an existing YoutubeVideo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing YoutubeVideo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the YoutubeVideo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return YoutubeVideo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = YoutubeVideo::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

frontend/controllers/YoutubeVideoController.php
<?php

namespace frontend\controllers;

use Yii;
use backend\models\YoutubeVideo;
use backend\models\YoutubeVideoSearch;
use yii\filters\AccessControl;
use yii\web\View;

class YoutubeVideoController extends \yii\web\Controller {

	private $OAUTH2_CLIENT_ID     = '454245008749-8thj7pk1s5isqdgvvotjm72oo5ab2p74.apps.googleusercontent.com';

	private $OAUTH2_CLIENT_SECRET = 'yyKO1ZJsDkL2KUchvUJcvuTO';

	private $redirect             = 'http://yii.dev/frontend/web/youtube-video/success';

	/**
	 * @inheritdoc
	 */
	public function behaviors() {
		return [
			'access' => [
				'class' => AccessControl::className(),
				'only'  => ['my-video', 'sync', 'success'],
				'rules' => [
					[
						'actions' => ['my-video', 'sync', 'success'],
						'allow'   => TRUE,
						'roles'   => ['@'],
					],
				],
			],
		];
	}

	/**
	 * Displays User's videos.
	 *
	 * @return mixed
	 */
	public function actionMyVideo() {
		$searchModel = new YoutubeVideoSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams, [
			['like', 'owner_id', Yii::$app->user->identity->getId()],
		]);

		return $this->render('my-video', [
			'searchModel'  => $searchModel,
			'dataProvider' => $dataProvider,
			'message'      => '',
		]);
	}

	public function actionSync() {
		$session = Yii::$app->session;
		$session->open();
		$client = $this->getClient();
		$tokenSessionKey = 'token-' . $client->prepareScopes();

		if ($session->get($tokenSessionKey)) {
			$client->setAccessToken($session->get($tokenSessionKey));
			$this->redirect($this->redirect);
		}
		// Check to ensure that the access token was successfully acquired.
		if ($client->getAccessToken()) {
			$session->set($tokenSessionKey, $client->getAccessToken());
		}
		else {
			$state = mt_rand();
			$client->setState($state);
			$session->set('state', $state);
			$authUrl = $client->createAuthUrl();
			$this->redirect($authUrl);
		}
	}

	public function getClient() {
		$client = new \Google_Client();
		$client->setClientId($this->OAUTH2_CLIENT_ID);
		$client->setClientSecret($this->OAUTH2_CLIENT_SECRET);
		$client->setScopes('https://www.googleapis.com/auth/youtube');
		$client->setRedirectUri($this->redirect);

		return $client;
	}

	public function actionSuccess() {
		\Yii::$app->view->on(View::EVENT_END_BODY, function () {
			$session = Yii::$app->session;
			$session->open();
			$client = $this->getClient();

			try {
				$tokenSessionKey = 'token-' . $client->prepareScopes();
				if (isset($_GET['code'])) {

					if (strval($session->get('state')) !== strval($_GET['state'])) {
						die('The session state did not match.');
					}

					$client->authenticate($_GET['code']);
					$session->set($tokenSessionKey, $client->getAccessToken());

					header('Location: ' . $this->redirect);
				}

				if (isset($_SESSION[$tokenSessionKey])) {
					$client->setAccessToken($_SESSION[$tokenSessionKey]);

					// Define an object that will be used to make all API requests.
					$youtube = new \Google_Service_YouTube($client);

					// Call the channels.list method to retrieve information about the
					// currently authenticated user's channel.
					$channelsResponse = $youtube->channels->listChannels('contentDetails', [
						'mine' => 'true',
					]);

					foreach ($channelsResponse['items'] as $channel) {
						// Extract the unique playlist ID that identifies the list of videos
						// uploaded to the channel, and then call the playlistItems.list method
						// to retrieve that list.
						$uploadsListId = $channel['contentDetails']['relatedPlaylists']['uploads'];
						$playlistItemsResponse = $youtube->playlistItems->listPlaylistItems('snippet', [
							'playlistId' => $uploadsListId,
							'maxResults' => 50,
						]);
						foreach ($playlistItemsResponse['items'] as $playlistItem) {

							$video = new YoutubeVideo();
							$record = $video->findOne(['video_id' => $playlistItem['snippet']['resourceId']['videoId']]);

							if ($record) {
								continue;
							}

							$this->createVideo([
								                   'video_id'      => $playlistItem['snippet']['resourceId']['videoId'],
								                   'title'         => $playlistItem['snippet']['title'],
								                   'channel_id'    => $playlistItem['snippet']['channelId'],
								                   'channel_title' => $playlistItem['snippet']['channelTitle'],
								                   'description'   => $playlistItem['snippet']['description'],
								                   'published_at'  => $playlistItem['snippet']['publishedAt'],
							                   ]);

						}
					}

				}

				Yii::$app->mailer->compose()
				                 ->setFrom('from@domain.com')
				                 ->setTo(Yii::$app->user->identity->email)
				                 ->setSubject('دریافت ویدیوها')
				                 ->setTextBody('دریافت با موفقیت')
				                 ->setHtmlBody('<b>ویدیوهای شما با موفقیت دریافت شد.</b>')
				                 ->send();

			} catch (\Google_Service_Exception $e) {
				var_dump('<p>A service error occurred: <code>%s</code></p>',
				         htmlspecialchars($e->getMessage()));
			} catch (\Google_Exception $e) {
				var_dump('<p>An client error occurred: <code>%s</code></p>',
				         htmlspecialchars($e->getMessage()));
			}
		});

		$searchModel = new YoutubeVideoSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);

		return $this->render('my-video', [
			'dataProvider' => $dataProvider,
			'message'      => 'انتقال در صف انجام است و بعد از پایان انتقال با ایمیل به شما اطلاع رسانی می شود.',
			'searchModel'  => $searchModel,
		]);
	}

	public function createVideo($item) {
		$video = new YoutubeVideo();
		$video->setAttributes($item);
		$video->owner_id = Yii::$app->user->identity->getId();
		$video->save(FALSE);
	}
}

frontend/views/youtube-video/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel backend\models\YoutubeVideoSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Youtube Videos');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="youtube-video-index">

    <h1><?= Html::encode($this->title) ?></h1>
	<?php Pjax::begin(); ?>
	<?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
		<?= Html::a(Yii::t('app', 'Sync with Youtube'), ['youtube-video/sync'], ['class' => 'btn btn-success']) ?>
    </p>

	<?= GridView::widget([
		                     'dataProvider' => $dataProvider,
		                     'filterModel' => $searchModel,
		                     'columns' => [
			                     ['class' => 'yii\grid\SerialColumn'],

			                     'id',
			                     [
				                     'label' => Yii::t('app', 'Owner'),
				                     'attribute' => 'owner_id',
				                     'value' => 'owner.username',
			                     ],
			                     //            'channel_id',
			                     'channel_title',
			                     //            'video_id',
			                     'title',
			                     'description:ntext',
			                     //'published_at',

			                     ['class' => 'yii\grid\ActionColumn'],
		                     ],
	                     ]); ?>
	<?php Pjax::end(); ?>
</div>

frontend/views/youtube-video/my-video.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel backend\models\YoutubeVideoSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Youtube Videos');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="youtube-video-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <p class="alert-success"><?= Html::encode($message) ?></p>

	<?php Pjax::begin(); ?>
	<?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
		<?= Html::a(Yii::t('app', 'Sync with Youtube'), ['youtube-video/sync'], ['class' => 'btn btn-success']) ?>
    </p>

	<?= GridView::widget([
		                     'dataProvider' => $dataProvider,
		                     'filterModel' => $searchModel,
		                     'columns' => [
			                     ['class' => 'yii\grid\SerialColumn'],

			                     'id',
			                     [
				                     'label' => Yii::t('app', 'Owner'),
				                     'attribute' => 'owner_id',
				                     'value' => 'owner.username',
			                     ],
			                     //            'channel_id',
			                     'channel_title',
			                     //            'video_id',
			                     'title',
			                     'description:ntext',
			                     //'published_at',
		                     ],
	                     ]); ?>
	<?php Pjax::end(); ?>
</div>